# Generated by Django 3.1.5 on 2021-01-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_showtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemaa',
            options={'verbose_name': 'سینما', 'verbose_name_plural': 'سینما'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم'},
        ),
        migrations.AlterModelOptions(
            name='showtime',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس'},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='free_saets',
        ),
        migrations.AddField(
            model_name='showtime',
            name='free_seats',
            field=models.IntegerField(default='100', verbose_name='صندلی های خالی'),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='cinema_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='کد سینما'),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='city',
            field=models.CharField(default='تهران', max_length=30, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='cinemaa',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=50, verbose_name='کارگردان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='سال ساخت'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='cinemaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.cinemaa', verbose_name='سینما'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.movie', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='salable_seats',
            field=models.IntegerField(verbose_name='صندلی های قابل فروش'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(verbose_name='شروع سانس'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش شروع نشده است'), (2, 'در حال فروش بلیط'), (3, 'بلیط تمام شد'), (4, 'فروش بلیط بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], verbose_name='وضعیت سانس'),
        ),
    ]
